language: dart
dart: [stable, beta, dev]

cache:
  timeout: 300
  bundler: true
  directories:
  - $HOME/.pub-cache
  - $HOME/.nvm
  - $HOME/.rvm
  - node_modules

env:
  global:
    - JEKYLL_ENV=production
    - TZ=US/Pacific # normalize build timestamp
  matrix:
    - TASK="./tool/translator/build.sh --check-links"
#   - TASK="./tool/check-code.sh"
#    - TASK="./tool/check-code.sh --null-safety"
    - TASK="./tool/analyze-and-test-examples.sh"
    - TASK="./tool/analyze-and-test-examples.sh --null-safety"

matrix:
  allow_failures:
    - env: TASK="./tool/analyze-and-test-examples.sh"
      dart: stable #TEMPORARY FIX
    - env: TASK="./tool/analyze-and-test-examples.sh"
      dart: beta
    - env: TASK="./tool/analyze-and-test-examples.sh"
      dart: dev
    - env: TASK="./tool/analyze-and-test-examples.sh --null-safety"
      dart: stable
    - env: TASK="./tool/analyze-and-test-examples.sh --null-safety"
      dart: beta
#     - env: TASK="./tool/check-code.sh --null-safety"
#       dart: stable
#     - env: TASK="./tool/check-code.sh --null-safety"
#       dart: beta

before_install:
  - source ./tool/env-set.sh
  - ./tool/before-install.sh

install:
  - ./tool/install.sh
  - ./tool/shared/write-ci-info.sh -v

script: $TASK

deploy:
  - provider: script
    script: ./tool/translator/deploy-cn.sh
    skip_cleanup: true
    on:
      repo: cfug/dart.cn
      branch: master
#      condition: $TASK == *build*
      condition: $TASK == *build* && $TRAVIS_DART_VERSION == stable && $TRAVIS_EVENT_TYPE == push

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [master, /^\d\.x$/, /^\d-dev$/, /travis-build/]
