name: build

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

env:
  # Keep for Dart SDK reporting
  PUB_ENVIRONMENT: bot.github
  # LTS
  NODE_VERSION: '16'
  # Tool location
  BASE_DIR: ${{ github.workspace }}
  TOOL_DIR: ${{ github.workspace }}/tool

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta, dev]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: tool/test.sh
        env:
          DART_CHANNEL: ${{ matrix.sdk }}

  deploy:
    permissions:
      checks: write
      pull-requests: write
    if: ${{ github.event_name == 'push' && 
            github.ref == 'refs/heads/master' && 
            github.repository == 'cfug/dart.cn' }}
    needs: test
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT: default
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          submodules: recursive
      - run: make build
      - run: make deploy
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
