name: build

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

env:
  # Keep for Dart SDK reporting
  PUB_ENVIRONMENT: bot.github
  # LTS
  NODE_VERSION: '18'
  # Tool location
  BASE_DIR: ${{ github.workspace }}
  TOOL_DIR: ${{ github.workspace }}/tool

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - sdk: stable
            experimental: false
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: tool/test.sh
        env:
          DART_CHANNEL: ${{ matrix.sdk }}

  deploy:
    permissions:
      checks: write
      pull-requests: write
    if: ${{ github.event_name == 'push' &&
            github.ref == 'refs/heads/main' &&
            github.repository == 'cfug/dart.cn' }}
    needs: test
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT: default
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          submodules: recursive
      - run: make build
      - run: make write-prod-robots
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: stable
      #- run: tool/check-links.sh
      - run: make deploy
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
